Excluded:
  - repositories/**/*.cr

Lint/DebugCalls:
  Excluded:
  - drivers/**/*_spec.cr

# NOTE: These should all be reviewed on an individual basis to see if their
#       complexity can be reasonably reduced.
Metrics/CyclomaticComplexity:
  Description: Disallows methods with a cyclomatic complexity higher than `MaxComplexity`
  MaxComplexity: 10
  Excluded:
  - drivers/jack/hello.cr
  Enabled: false
  Severity: Convention

Lint/UselessAssign:
  Description: Disallows useless variable assignments
  # NOTE: Not enabled due to the extremely large hit count.
  #       Discussion with driver authors on whether this pattern is intended.
  Enabled: false
  Severity: Warning

Style/VerboseBlock:
  Description: Identifies usage of collapsible single expression blocks.
  ExcludeCallsWithBlock: false
  ExcludeMultipleLineBlocks: true
  ExcludeOperators: false
  ExcludePrefixOperators: false
  ExcludeSetters: true
  Enabled: false
  Severity: Convention

Style/VariableNames:
  Description: Enforces variable names to be in underscored case
  # NOTE: Not enabled due to the extremely large hit count.
  #       Discussion with driver authors on whether this pattern is intended.
  Enabled: false
  Severity: Convention

# NOTE: These appear to be triggered by assignment in case expressions, could be an ameba bug
Lint/ShadowingOuterLocalVar:
  Description: Disallows the usage of the same name as outer local variables for block
    or proc arguments.
  Excluded:
  - drivers/cisco/switch/snooping_catalyst.cr
  Enabled: true
  Severity: Warning
